const HEROICON_FALLBACKS: Record<string, string> = {
  "computer-desktop": "💻",
  "chart-bar-square": "📊",
  "chart-bar": "📊",
  "gift": "🎁",
  "briefcase": "💼",
  "currency-dollar": "💰",
  "banknotes": "💵",
  "home": "🏠",
  "home-modern": "🏠",
  "shopping-cart": "🛒",
  "shopping-bag": "🛍️",
  "heart": "❤️",
  "academic-cap": "🎓",
  "truck": "🚚",
  "musical-note": "🎵",
  "film": "🎬",
  "device-phone-mobile": "📱",
  "building-office": "🏢",
  "building-office-2": "🏢",
  "sparkles": "✨",
  "star": "⭐",
  "fire": "🔥",
  "bolt": "⚡",
  "globe-alt": "🌍",
  "globe-americas": "🌍",
  "user": "👤",
  "users": "👥",
  "car": "🚗",
  "airplane": "✈️",
  "cake": "🎂",
  "beaker": "🧪",
  "book-open": "📖",
  "credit-card": "💳",
  "tag": "🏷️",
  "wrench": "🔧",
  "paint-brush": "🎨",
  "camera": "📷",
  "device-tablet": "📱",
  "wifi": "📶",
  "light-bulb": "💡",
  "leaf": "🌿",
  "sun": "☀️",
  "moon": "🌙",
  "paw-print": "🐾",
  "face-smile": "😊",
};

export function resolveIcon(icon?: string | null, fallback = "📁"): string {
  if (!icon) return fallback;
  return HEROICON_FALLBACKS[icon] ?? icon;
}
